FROM ubuntu:trusty
MAINTAINER Mark Waser <mark@artificialgeneralintelligenceinc.com>
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /shared


RUN apt-get update && \
apt-get -yq install ruby apache2 git apt-cacher-ng python-vm-builder qemu-kvm qemu-utils

RUN git clone https://github.com/kleetus/gitian-builder.git
RUN git clone https://github.com/pivx-project/gitian.sigs.git
RUN git clone https://github.com/pivx-project/pivx-detached-sigs.git
RUN git clone https://github.com/pivx-project/pivx.git

RUN cd pivx && export SIGNER=mwaser && \
export VERSION=3.0.6 && \
git fetch && \
git checkout v${VERSION}

RUN cd gitian-builder && \
mkdir -p inputs && \
wget -P inputs https://bitcoincore.org/cfields/osslsigncode-Backports-to-1.7.1.patch && \
wget -P inputs http://downloads.sourceforge.net/project/osslsigncode/osslsigncode/osslsigncode-1.7.1.tar.gz

RUN useradd -d /home/ubuntu -m -s /bin/bash ubuntu && echo "ubuntu:ubuntu" | chpasswd  && adduser ubuntu sudo && \
chown -R ubuntu.ubuntu /shared/ && \
chown root.root /shared/gitian-builder/target-bin/grab-packages.sh && \
chmod 755 /shared/gitian-builder/target-bin/grab-packages.sh && \
echo 'ubuntu ALL=(root) NOPASSWD:/usr/bin/apt-get,/shared/gitian-builder/target-bin/grab-packages.sh' > /etc/sudoers.d/ubuntu && \
chown root.root /etc/sudoers.d/ubuntu && \
chmod 0400 /etc/sudoers.d/ubuntu && \
chown -R ubuntu.ubuntu /home/ubuntu
USER ubuntu

RUN printf "cd /shared/gitian-builder; \
sudo ./bin/gbuild --upgrade --skip-image --commit pivx=\$1 \$3" > /home/ubuntu/runit.sh
# CMD ["v3.0.6","https://github.com/MWaser/pivx.git","../pivx/contrib/gitian-descriptors/gitian-linux.yml"]
# ENTRYPOINT ["bash", "/home/ubuntu/runit.sh"]


# ./bin/gbuild --skip-image --commit pivx=\$1 --url pivx=\$2 \$3
# RUN sudo bash -c '[[ -d /shared/gitian-builder ]] || bin/gbuild --memory 3000 --commit pivx=v${VERSION} ../pivx/contrib/gitian-descriptors/gitian-linux.yml'
# RUN sudo bash -c '[[ -d /shared/gitian-builder ]] || bin/gsign --signer $SIGNER --release ${VERSION}-linux --destination ../gitian.sigs/ ../pivx/contrib/gitian-descriptors/gitian-linux.yml'
# mv build/out/pivx-*.tar.gz build/out/src/pivx-*.tar.gz ../



